### ISSUE TITLE
4.2.0.1 brakes specs that are running with 4.1.0

### ISSUE THREAD

**Issue by thebravoman** [knapo/mustache-js-rails#5]
Hi,
We are running specs everyday.
After bundle update the changes are

```
Fetching websocket-driver 0.7.5 (was 0.7.4)
Fetching mustache-js-rails 4.2.0.1 (was 4.1.0)
Installing mustache-js-rails 4.2.0.1 (was 4.1.0)
Installing websocket-driver 0.7.5 (was 0.7.4) with native extensions
```

The error that occurs is 
```
mustache.self-b94add…ffe2f1673523.js:765 Uncaught SyntaxError: Unexpected token 'export'
```

and in the teaspoon specs

````
ReferenceError: Mustache is not defined
ReferenceError: Mustache is not defined
````

I am trying to dig deeper and understand what exactly has happened

Ruby 2.6.5
Rails 6.1

**Comment by thebravoman** [comment]
Attaching a screenshot of the error 

Hope it helps

![Screenshot from 2021-06-13 21-29-59](https://user-images.githubusercontent.com/1311493/121818242-a0323780-cc8e-11eb-97c8-dccc00ae93b0.png)

**Comment by knapo** [comment]
Looks like mustache 4.2 compatibility issue, I releases `4.1.0.1` and yanked `4.2.0.1`. Can you downgrade and check ?  Hope that helps.

I no longer use `rails` and `mustache-js-rails` in any of my projects and not able to easily test (PRs are welcome!)

**Comment by thebravoman** [comment]
Tried with 4.1.0.1 

Still the same error. 

I can probably migrate to using mustache from npm for my projects. Will check if it will be easier for a PR

**Comment by knapo** [comment]
@thebravoman Released 4.1.0.2 - can you try now?

**Comment by thebravoman** [comment]
I will try in a moment in order to report to you, but I've decided to migrate to npm.

For anyone looking for how it is:
```

--- a/app/javascript/packs/application.js
+++ b/app/javascript/packs/application.js
@@ -15,5 +15,7 @@
+window.Mustache = require("mustache");

--- a/is-babylon_scene.gemspec
+++ b/is-babylon_scene.gemspec
 
-  spec.add_dependency "mustache", "~> 1.0"
-  spec.add_dependency 'mustache-js-rails'
-  spec.add_development_dependency "mustache", "~> 1.0"
-  spec.add_development_dependency 'mustache-js-rails'

package.json
@@ -4,7 +4,8 @@
   "dependencies": {
+    "mustache": "^4.2.0"
   },

```
add then

```
-//= require mustache
```
for every other file.

**Comment by thebravoman** [comment]
@knapo 4.1.0.2 did not solve the problem

```
SyntaxError: export declarations may only appear at top level of a module
```

**Comment by thebravoman** [comment]
Well, I migrated all of my platforms to npm except one, probably the most important one, as it still depends heavily on sprockets, so it was not as easy as using it from npm.
